Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,9 +8,9 @@ jobs:
     steps:
       - name: Trigger Deployment CI
         run: |
-          echo "Coming from IP $(curl ip.lee.io)"
+          echo "Triggering CI from IP $(curl ip.lee.io)"
           curl -X POST --silent --connect-timeout 20 -F "ref=master" -F token=$TRIGGER_TOKEN $PROJECT_URL > /dev/null
-          if [ $? -ne 0 ] ; then echo "Failed to trigger pipeline"; fi
+        #  if [ $? -ne 0 ] ; then echo "Failed to trigger pipeline"; fi
         env:
           TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
           PROJECT_URL: ${{ secrets.PROJECT_URL }}
