ci

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,16 +1,16 @@
 name: Deploy
 on:
   push:
-    branches:
-      - main
+    branches: [ master, main ]
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - shell: bash
-        env:
-          GITLAB_PIPELINE_TRIGGER_TOKEN: ${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }}
+      - name: Trigger Deployment CI
         run: |
-          curl -X POST --connect-timeout 20 -F "ref=master" -F token=$GITLAB_PIPELINE_TRIGGER_TOKEN https://gitlab.devops.ukfast.co.uk/api/v4/projects/2570/trigger/pipeline
-          if [ $? -eq 0 ]; then echo "Successfully triggered pipeline"; else echo "Failed to trigger pipeline"; fi
-        
+          /sbin/ip a
+          curl -X POST --connect-timeout 20 -F "ref=master" -F token=$TRIGGER_TOKEN $PROJECT_URL
+          if [ $? -ne 0 ] ; then echo "Failed to trigger pipeline"; fi
+        env:
+          TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
+          PROJECT_URL: ${{ secrets.PROJECT_URL }}
